const Projects = [
    {
        src: "test.png",
        title: "iLMS",
        description: "iSort Library Management System via C++ TUI",
        codeUrl: "https://github.com/dreyyan/Project.01.iLMS",
    },
    {
        src: "test.png",
        title: "A.A.V.S.S.",
        description: "Advanced Automated Vehicular Storage & Simulation System",
        codeUrl: "https://github.com/dreyyan/Project.02.AAVSS",
    },
    {
        src: "test.png",
        title: "Website - Software Development",
        description: "First Website using HTML, CSS, and JS",
        codeUrl: "https://github.com/dreyyan/Project.03.Website-SofDev",
    },
    {
        src: "test.png",
        title: "QuizMake",
        description: "Quiz Desktop Application for Students/Learners",
        codeUrl: "https://github.com/dreyyan/Project.04.QuizMake",
    },
    {
        src: "test.png",
        title: "Exodia",
        description: "Text-based Fantasy RPG",
        codeUrl: "https://github.com/dreyyan/Project.05.Exodia",
    },
    {
        src: "test.png",
        title: "ViCalc",
        description: "Dynamic Text-based Virtual Calculator ",
        codeUrl: "https://github.com/dreyyan/Project.06.ViCalc",
    },
    {
        src: "test.png",
        title: "A.U.T.O.M.A.",
        description: "Advanced Utility Task-Optimized Machine Assistant",
        codeUrl: "https://github.com/dreyyan/Project.07.AUTOMA",
    },
    {
        src: "test.png",
        title: "CashGO+",
        description: "Bank Management System via Python TUI",
        codeUrl: "https://github.com/dreyyan/Project.08.CashGO",
    },
    {
        src: "test.png",
        title: "WeLearn Student Management System",
        description: "WeLearn Student Portal Management System via Python TUI",
        codeUrl: "https://github.com/dreyyan/Project.Project.09.Welearn_Student_M.S",
    },
    {
        src: "test.png",
        title: "WeLearn",
        description: "A One-Stop Mobile Portal App for Students, Teachers, and School Management",
        codeUrl: "https://github.com/dreyyan/Project.10.WeLearn",
    },
    {
        src: "test.png",
        title: "Tasky",
        description: "An NLP-based A.I. Task Assistant",
        codeUrl: "https://github.com/dreyyan/Project.11.Tasky",
    },
    {
        src: "test.png",
        title: "I.L.G.Y.L.",
        description: "If Life Gives You Lemons: A Gamified Lemonade Business Tycoon Simulation System",
        codeUrl: "https://github.com/dreyyan/Project.12.ILGYL",
    },
    {
        src: "test.png",
        title: "React Native Template",
        description: "Mobile Application Template via React Native Framework",
        codeUrl: "https://github.com/dreyyan/Project.13.ReactNativeTemplate",
    },
    {
        src: "test.png",
        title: "My Historical Journey",
        description: "A Website Showcasing Filipino History via React Framework",
        codeUrl: "https://github.com/dreyyan/Project.1.",
    },
    {
        src: "test.png",
        title: "Jack-n-Po",
        description: "A 'Rock, Paper, Scissors' Game via Python TUI",
        codeUrl: "https://github.com/dreyyan/Project.15.Jack-n-Po",
    },
    {
        src: "test.png",
        title: "AutoMail",
        description: "Email Automation System",
        codeUrl: "https://github.com/dreyyan/Project.16.AutoMail",
    },
    {
        src: "test.png",
        title: "RandoMania",
        description: "Random Character Generator via JavaScript Object-Oriented Programming",
        codeUrl: "https://github.com/dreyyan/Project.17.RandoMania",
    },
    {
        src: "test.png",
        title: "Project.18.BingeMatch",
        description: "Movie Database & Recommender System via Classification Model",
        codeUrl: "https://github.com/dreyyan/Project.18.BingeMatch",
    },
    {
        src: "test.png",
        title: "HealthLink",
        description: "A Gradient Boosting AI Model for Disease and Symptom Classification",
        codeUrl: "https://github.com/dreyyan/Project.19.HealthLink",
    },
    {
        src: "test.png",
        title: "Fizz-Up!",
        description: "An Offline Crypto Miner-like Drink Machine Game via Java TUI",
        codeUrl: "https://github.com/dreyyan/Project.21.FizzUp",
    },
    {
        src: "test.png",
        title: "nCrypT",
        description: "A Cryptic Cipher Game System via Java",
        codeUrl: "https://github.com/dreyyan/Project.22.nCrypT",
    },
    {
        src: "test.png",
        title: "React Tempate",
        description: "Website Template via React Framework",
        codeUrl: "https://github.com/dreyyan/Project.23.ReactTemplate",
    },
    {
        src: "test.png",
        title: "Yellow Basket",
        description: "An e-commerce React Website",
        codeUrl: "https://github.com/dreyyan/Project.24.YellowBasket",
    },
    {
        src: "test.png",
        title: "SalaRate",
        description: "An Employee Salary Calculator Website",
        codeUrl: "https://github.com/dreyyan/Project.25.SalaRate",
    },
    {
        src: "test.png",
        title: "Project.26.Systemate",
        description: "A Java Library for Easy Console Development",
        codeUrl: "https://github.com/dreyyan/Project.26.Systemate",
    },
    {
        src: "test.png",
        title: "Personal Website",
        description: "A Personal Website - About Me, Portfolio, and Resume",
        codeUrl: "https://github.com/dreyyan/Project.27.PersonalWebsite",
    },
];

export default Projects;